package jp.hanatoya.evidence.fcm.repo;

import org.greenrobot.greendao.annotation.*;
import org.parceler.Parcel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOTICE".
 */
@Entity
@Parcel
public class Notice {

    @Id(autoincrement = true)
     Long id;
     String message;
     String title;
     long ts;

    @Generated
    public Notice() {
    }

    public Notice(Long id) {
        this.id = id;
    }

    @Generated
    public Notice(Long id, String message, String title, long ts) {
        this.id = id;
        this.message = message;
        this.title = title;
        this.ts = ts;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public long getTs() {
        return ts;
    }

    public void setTs(long ts) {
        this.ts = ts;
    }

}
